package main.buildings.base;

public enum BuildingType {
    TOWN_HALL, STORAGE, FARM, CLAY_PIT, LUMBERJACK, QUARRY,
    BARRACKS, MARKET, UNIVERSITY, BLACKSMITH, STABLES, WALLS, TOWERS,
    STONE_MASON, SAWMILL, BRICKWORKS, IRON_FORGE
}
